spring:
  cloud:
    gateway:
      routes:
        #        - id: test_route
        #          uri: https://www.baidu.com
        #          predicates:
        #            - Query=url,baidu
        #        - id: qq_route
        #          uri: https://www.qq.com
        #          predicates:
        #            - Query=url,qq
        #lb代表 负载均衡  loadBalance   只要请求有api前缀的请求，默认路由到负载均衡renren-fast
        #自定义规则：前端的项目,/api前缀     uri 表示负载均衡到xx个服务
        # 配置商品路由：所有由/api/product/**请求开始的都路由到hahamall-product商品服务
        - id: third_party_route
          uri: lb://hahamall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: product_route
          uri: lb://hahamall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: coupon_route
          uri: lb://hahamall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://hahamall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://hahamall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: hahamall_host_route
          uri: lb://hahamall-product
          predicates:
            - Host=hahamall.com,item.hahamall.com

        - id: hahamall_search_route
          uri: lb://hahamall-search
          predicates:
            - Host=search.hahamall.com

        - id: hahamall_auth_route
          uri: lb://hahamall-auth-server
          predicates:
            - Host=auth.hahamall.com

        - id: hahamall_seckill_route
          uri: lb://hahamall-seckill
          predicates:
            - Host=seckill.hahamall.com
#            - RewritePath=/red/?(?<segment>.*), /$\{segment}
#http://localhost:88/api/captcha.jpg   --> http://renren-fast:8080/api/captcha.jpg
#但是实际上需要转化成  http://localhost:8080/renren-fast/captcha.jpg  因此需要添加【filters】去重写路径
